version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
    - 3360:3360
    environment:
        MYSQL_ROOT_PASSWORD: gP6eeaum
        MYSQL_DATABASE: mybb
        MYSQL_USER: mybb
        MYSQL_PASSWORD: gP6eeaum



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080