version: "3.1"

services:
  #angular: # name of the first service
    #build: knittingApp # specify the directory of the Dockerfile
    #ports:
      #- "4200:4200" # specify port forewarding

  express:
    build: node.rest.api
    ports:
      - "6001:6001"
    links:
      - db

  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: shegg

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
