version: '2'

services:
    angular: # name of the first service
        build: angular-client # specify the directory of the Dockerfile
        ports:
            - "4200:4200" # specify port forewarding

services:
    express:
        build: backend
        ports:
            - "3000:3000"
        links:
            - database

    database:
        image: mongo
        ports:
            - "27017:27017"
