version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    ports:
    - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: gP6eeaum
        MYSQL_DATABASE: testdb
        MYSQL_USER: iqo
        MYSQL_PASSWORD: gP6eeaum



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080